### ISSUE TITLE
Errors compiling mbrtud

### ISSUE THREAD

**Issue by ggalt** [Telegea/Smartbox-software#1]
Initially, I had to modify the Makefile in this directory to add a path the modbus.h.  Once I did that, I received a bunch of compile errors.  My assumption is that I'm on a different version of libmodbus.  I'm using Raspian Wheezy from Adafruit (since I need their kernel to support my 2.8" capacitive touchscreen).

Here is the output from dpkg-query:

` dpkg-query -l | grep libmodbus
ii  libmodbus-dev                  3.0.6-1                      armhf        development files for the Modbus protocol library
ii  libmodbus5:armhf               3.0.6-1                      armhf        library for the Modbus protocol`

The output from gcc I get is:

> make[1]: Entering directory '/root/modules/mbrtud'
--- Compile and Linking all object files to create the whole file: mbrtud ---
gcc mbrtud.c -o mbrtud  -I. -I/usr/include/modbus -Wformat=2 -Wall -Winline  -pipe -fPIC  -lmbsrv -lmodbus
mbrtud.c: In function ‘main’:
mbrtud.c:247:36: warning: passing argument 2 of ‘modbus_set_response_timeout’ makes pointer from integer without a cast
    modbus_set_response_timeout(mb, 5, 0);
                                    ^
In file included from mbrtud.c:44:0:
/usr/include/modbus/modbus.h:151:6: note: expected ‘const struct timeval *’ but argument is of type ‘int’
 void modbus_set_response_timeout(modbus_t *ctx, const struct timeval *timeout);
      ^
mbrtud.c:247:4: error: too many arguments to function ‘modbus_set_response_timeout’
    modbus_set_response_timeout(mb, 5, 0);
    ^
In file included from mbrtud.c:44:0:
/usr/include/modbus/modbus.h:151:6: note: declared here
 void modbus_set_response_timeout(modbus_t *ctx, const struct timeval *timeout);
      ^
mbrtud.c:248:32: warning: passing argument 2 of ‘modbus_set_byte_timeout’ makes pointer from integer without a cast
    modbus_set_byte_timeout(mb, 1, 0);
                                ^
In file included from mbrtud.c:44:0:
/usr/include/modbus/modbus.h:154:6: note: expected ‘const struct timeval *’ but argument is of type ‘int’
 void modbus_set_byte_timeout(modbus_t *ctx, const struct timeval *timeout);
      ^
mbrtud.c:248:4: error: too many arguments to function ‘modbus_set_byte_timeout’
    modbus_set_byte_timeout(mb, 1, 0);
    ^
In file included from mbrtud.c:44:0:
/usr/include/modbus/modbus.h:154:6: note: declared here
 void modbus_set_byte_timeout(modbus_t *ctx, const struct timeval *timeout);
      ^
mbrtud.c:254:7: warning: implicit declaration of function ‘modbus_rtu_set_rts’ [-Wimplicit-function-declaration]
       if (modbus_rtu_set_rts(mb, MODBUS_RTU_RTS_DOWN) == -1)
       ^
mbrtud.c:254:34: error: ‘MODBUS_RTU_RTS_DOWN’ undeclared (first use in this function)
       if (modbus_rtu_set_rts(mb, MODBUS_RTU_RTS_DOWN) == -1)
                                  ^
mbrtud.c:254:34: note: each undeclared identifier is reported only once for each function it appears in
mbrtud.c:265:10: warning: implicit declaration of function ‘modbus_rtu_set_rts_delay’ [-Wimplicit-function-declaration]
          if (modbus_rtu_set_rts_delay(mb, DEFAULT_RTS_DELAY) == -1)
          ^
Makefile:26: recipe for target 'target' failed
make[1]: *** [target] Error 1
make[1]: Leaving directory '/root/modules/mbrtud'
Makefile:14: recipe for target 'target' failed
make: *** [target] Error 2

Any thoughts?

**Comment by ondrej1024** [comment]
>  My assumption is that I'm on a different version of libmodbus.

Yes you are right. With the latest changes to mbrtud we need the 3.1.x branch of libmodbus. This has to be installed from source since on older Raspbian versions no packages are available for it.

Anyway there have been a lot of code changes lately which are not in GitHub yet. And also the documentation is being updated. All this will be pushed to the repo in the next days so you can use the latest source code files.

**Comment by ondrej1024** [comment]
> I'm using Raspian Wheezy from Adafruit (since I need their kernel to support my 2.8" capacitive touchscreen).

You could try to use our [latest SD card image](https://github.com/Telegea/Smartbox-software/releases/tag/V2.2) which has already everything installed, including touchscreen support. The Adafruit Raspbian version is not needed any more for the touchscreen to work. Both the resistive and capacitive touch screen drivers are in the official RPi kernel now.

**Comment by ggalt** [comment]
Great!  Thanks.  FYI, I noticed a typo on your current installation instructions:
`scp device/src/thermostat/Gui/themostat-gui.sh root@<device-ip-addr>:/usr/local/bin/`
should be:
`scp device/src/thermostat/Gui/thermostat-gui.sh root@<device-ip-addr>:/usr/local/bin/`

**Comment by ondrej1024** [comment]
Latest code updates are pushed to the repo now. Also typo was corrected.
